// flow-typed signature: dd78126fc6afd334391a972b32f68a72
// flow-typed version: <<STUB>>/babel-plugin-transform-relay-hot_v^1.0.4/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-relay-hot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-relay-hot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-transform-relay-hot/index' {
  declare module.exports: $Exports<'babel-plugin-transform-relay-hot'>;
}
declare module 'babel-plugin-transform-relay-hot/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-relay-hot'>;
}
