// flow-typed signature: d37a7b32c2d47c04809dbcb719e2b95b
// flow-typed version: <<STUB>>/babel-polyfill_v7.0.0-beta.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-polyfill/browser' {
  declare module.exports: any;
}

declare module 'babel-polyfill/dist/polyfill' {
  declare module.exports: any;
}

declare module 'babel-polyfill/dist/polyfill.min' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.array.copy-within' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.array.fill' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.array.find-index' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.array.find' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.array.from' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.array.iterator' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.array.of' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.function.name' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.map' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.math.acosh' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.math.asinh' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.math.atanh' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.math.cbrt' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.math.clz32' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.math.cosh' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.math.expm1' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.math.fround' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.math.hypot' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.math.imul' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.math.log10' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.math.log1p' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.math.log2' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.math.sign' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.math.sinh' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.math.tanh' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.math.trunc' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.number.epsilon' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.number.is-finite' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.number.is-integer' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.number.is-nan' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.number.is-safe-integer' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.number.max-safe-integer' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.number.min-safe-integer' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.number.parse-float' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.number.parse-int' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.object.assign' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.object.is' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.object.set-prototype-of' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.promise' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.apply' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.construct' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.define-property' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.delete-property' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.get-own-property-descriptor' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.get-prototype-of' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.get' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.has' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.is-extensible' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.own-keys' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.prevent-extensions' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.set-prototype-of' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.set' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.regexp.flags' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.regexp.match' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.regexp.replace' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.regexp.search' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.regexp.split' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.set' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.string.code-point-at' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.string.ends-with' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.string.from-code-point' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.string.includes' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.string.raw' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.string.repeat' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.string.starts-with' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.symbol' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.typed.array-buffer' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.typed.data-view' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.typed.float32-array' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.typed.float64-array' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.typed.int16-array' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.typed.int32-array' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.typed.int8-array' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.typed.uint16-array' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.typed.uint32-array' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.typed.uint8-array' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.typed.uint8-clamped-array' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.weak-map' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es6.weak-set' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es7.array.includes' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es7.object.entries' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es7.object.get-own-property-descriptors' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es7.object.values' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es7.string.pad-end' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/es7.string.pad-start' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/web.dom.iterable' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/web.immediate' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/core-js/modules/web.timers' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/index' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/regenerator-runtime/runtime' {
  declare module.exports: any;
}

declare module 'babel-polyfill/scripts/make-separate-polyfill-files' {
  declare module.exports: any;
}

declare module 'babel-polyfill/scripts/postpublish' {
  declare module.exports: any;
}

declare module 'babel-polyfill/scripts/prepublish' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-polyfill/browser.js' {
  declare module.exports: $Exports<'babel-polyfill/browser'>;
}
declare module 'babel-polyfill/dist/polyfill.js' {
  declare module.exports: $Exports<'babel-polyfill/dist/polyfill'>;
}
declare module 'babel-polyfill/dist/polyfill.min.js' {
  declare module.exports: $Exports<'babel-polyfill/dist/polyfill.min'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.array.copy-within.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.array.copy-within'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.array.fill.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.array.fill'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.array.find-index.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.array.find-index'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.array.find.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.array.find'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.array.from.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.array.from'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.array.iterator.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.array.iterator'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.array.of.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.array.of'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.function.name.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.function.name'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.map.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.map'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.math.acosh.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.math.acosh'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.math.asinh.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.math.asinh'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.math.atanh.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.math.atanh'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.math.cbrt.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.math.cbrt'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.math.clz32.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.math.clz32'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.math.cosh.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.math.cosh'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.math.expm1.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.math.expm1'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.math.fround.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.math.fround'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.math.hypot.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.math.hypot'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.math.imul.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.math.imul'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.math.log10.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.math.log10'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.math.log1p.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.math.log1p'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.math.log2.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.math.log2'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.math.sign.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.math.sign'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.math.sinh.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.math.sinh'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.math.tanh.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.math.tanh'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.math.trunc.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.math.trunc'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.number.epsilon.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.number.epsilon'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.number.is-finite.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.number.is-finite'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.number.is-integer.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.number.is-integer'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.number.is-nan.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.number.is-nan'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.number.is-safe-integer.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.number.is-safe-integer'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.number.max-safe-integer.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.number.max-safe-integer'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.number.min-safe-integer.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.number.min-safe-integer'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.number.parse-float.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.number.parse-float'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.number.parse-int.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.number.parse-int'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.object.assign.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.object.assign'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.object.is.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.object.is'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.object.set-prototype-of.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.object.set-prototype-of'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.promise.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.promise'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.apply.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.reflect.apply'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.construct.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.reflect.construct'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.define-property.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.reflect.define-property'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.delete-property.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.reflect.delete-property'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.get-own-property-descriptor.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.reflect.get-own-property-descriptor'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.get-prototype-of.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.reflect.get-prototype-of'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.get.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.reflect.get'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.has.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.reflect.has'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.is-extensible.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.reflect.is-extensible'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.own-keys.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.reflect.own-keys'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.prevent-extensions.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.reflect.prevent-extensions'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.set-prototype-of.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.reflect.set-prototype-of'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.reflect.set.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.reflect.set'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.regexp.flags.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.regexp.flags'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.regexp.match.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.regexp.match'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.regexp.replace.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.regexp.replace'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.regexp.search.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.regexp.search'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.regexp.split.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.regexp.split'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.set.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.set'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.string.code-point-at.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.string.code-point-at'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.string.ends-with.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.string.ends-with'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.string.from-code-point.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.string.from-code-point'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.string.includes.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.string.includes'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.string.raw.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.string.raw'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.string.repeat.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.string.repeat'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.string.starts-with.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.string.starts-with'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.symbol.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.symbol'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.typed.array-buffer.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.typed.array-buffer'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.typed.data-view.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.typed.data-view'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.typed.float32-array.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.typed.float32-array'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.typed.float64-array.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.typed.float64-array'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.typed.int16-array.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.typed.int16-array'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.typed.int32-array.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.typed.int32-array'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.typed.int8-array.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.typed.int8-array'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.typed.uint16-array.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.typed.uint16-array'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.typed.uint32-array.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.typed.uint32-array'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.typed.uint8-array.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.typed.uint8-array'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.typed.uint8-clamped-array.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.typed.uint8-clamped-array'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.weak-map.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.weak-map'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es6.weak-set.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es6.weak-set'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es7.array.includes.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es7.array.includes'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es7.object.entries.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es7.object.entries'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es7.object.get-own-property-descriptors.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es7.object.get-own-property-descriptors'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es7.object.values.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es7.object.values'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es7.string.pad-end.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es7.string.pad-end'>;
}
declare module 'babel-polyfill/lib/core-js/modules/es7.string.pad-start.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/es7.string.pad-start'>;
}
declare module 'babel-polyfill/lib/core-js/modules/web.dom.iterable.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/web.dom.iterable'>;
}
declare module 'babel-polyfill/lib/core-js/modules/web.immediate.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/web.immediate'>;
}
declare module 'babel-polyfill/lib/core-js/modules/web.timers.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/core-js/modules/web.timers'>;
}
declare module 'babel-polyfill/lib/index.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/index'>;
}
declare module 'babel-polyfill/lib/regenerator-runtime/runtime.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/regenerator-runtime/runtime'>;
}
declare module 'babel-polyfill/scripts/make-separate-polyfill-files.js' {
  declare module.exports: $Exports<'babel-polyfill/scripts/make-separate-polyfill-files'>;
}
declare module 'babel-polyfill/scripts/postpublish.js' {
  declare module.exports: $Exports<'babel-polyfill/scripts/postpublish'>;
}
declare module 'babel-polyfill/scripts/prepublish.js' {
  declare module.exports: $Exports<'babel-polyfill/scripts/prepublish'>;
}
