// flow-typed signature: e0f5893da3b82585396bcf3fca6ae7f5
// flow-typed version: <<STUB>>/escope_v3.6.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'escope'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'escope' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'escope/gulpfile' {
  declare module.exports: any;
}

declare module 'escope/lib/definition' {
  declare module.exports: any;
}

declare module 'escope/lib/index' {
  declare module.exports: any;
}

declare module 'escope/lib/pattern-visitor' {
  declare module.exports: any;
}

declare module 'escope/lib/reference' {
  declare module.exports: any;
}

declare module 'escope/lib/referencer' {
  declare module.exports: any;
}

declare module 'escope/lib/scope-manager' {
  declare module.exports: any;
}

declare module 'escope/lib/scope' {
  declare module.exports: any;
}

declare module 'escope/lib/variable' {
  declare module.exports: any;
}

declare module 'escope/powered-test/arguments' {
  declare module.exports: any;
}

declare module 'escope/powered-test/catch-scope' {
  declare module.exports: any;
}

declare module 'escope/powered-test/es6-arrow-function-expression' {
  declare module.exports: any;
}

declare module 'escope/powered-test/es6-block-scope' {
  declare module.exports: any;
}

declare module 'escope/powered-test/es6-catch' {
  declare module.exports: any;
}

declare module 'escope/powered-test/es6-class' {
  declare module.exports: any;
}

declare module 'escope/powered-test/es6-destructuring-assignments' {
  declare module.exports: any;
}

declare module 'escope/powered-test/es6-export' {
  declare module.exports: any;
}

declare module 'escope/powered-test/es6-import' {
  declare module.exports: any;
}

declare module 'escope/powered-test/es6-iteration-scope' {
  declare module.exports: any;
}

declare module 'escope/powered-test/es6-object' {
  declare module.exports: any;
}

declare module 'escope/powered-test/es6-rest-args' {
  declare module.exports: any;
}

declare module 'escope/powered-test/es6-switch' {
  declare module.exports: any;
}

declare module 'escope/powered-test/es6-template-literal' {
  declare module.exports: any;
}

declare module 'escope/powered-test/function-expression-name' {
  declare module.exports: any;
}

declare module 'escope/powered-test/global-increment' {
  declare module.exports: any;
}

declare module 'escope/powered-test/implicit-global-reference' {
  declare module.exports: any;
}

declare module 'escope/powered-test/label-children' {
  declare module.exports: any;
}

declare module 'escope/powered-test/label' {
  declare module.exports: any;
}

declare module 'escope/powered-test/nodejs-scope' {
  declare module.exports: any;
}

declare module 'escope/powered-test/object-expression' {
  declare module.exports: any;
}

declare module 'escope/powered-test/optimistic' {
  declare module.exports: any;
}

declare module 'escope/powered-test/with-scope' {
  declare module.exports: any;
}

declare module 'escope/src/definition' {
  declare module.exports: any;
}

declare module 'escope/src/index' {
  declare module.exports: any;
}

declare module 'escope/src/pattern-visitor' {
  declare module.exports: any;
}

declare module 'escope/src/reference' {
  declare module.exports: any;
}

declare module 'escope/src/referencer' {
  declare module.exports: any;
}

declare module 'escope/src/scope-manager' {
  declare module.exports: any;
}

declare module 'escope/src/scope' {
  declare module.exports: any;
}

declare module 'escope/src/variable' {
  declare module.exports: any;
}

declare module 'escope/third_party/espree' {
  declare module.exports: any;
}

// Filename aliases
declare module 'escope/gulpfile.js' {
  declare module.exports: $Exports<'escope/gulpfile'>;
}
declare module 'escope/lib/definition.js' {
  declare module.exports: $Exports<'escope/lib/definition'>;
}
declare module 'escope/lib/index.js' {
  declare module.exports: $Exports<'escope/lib/index'>;
}
declare module 'escope/lib/pattern-visitor.js' {
  declare module.exports: $Exports<'escope/lib/pattern-visitor'>;
}
declare module 'escope/lib/reference.js' {
  declare module.exports: $Exports<'escope/lib/reference'>;
}
declare module 'escope/lib/referencer.js' {
  declare module.exports: $Exports<'escope/lib/referencer'>;
}
declare module 'escope/lib/scope-manager.js' {
  declare module.exports: $Exports<'escope/lib/scope-manager'>;
}
declare module 'escope/lib/scope.js' {
  declare module.exports: $Exports<'escope/lib/scope'>;
}
declare module 'escope/lib/variable.js' {
  declare module.exports: $Exports<'escope/lib/variable'>;
}
declare module 'escope/powered-test/arguments.js' {
  declare module.exports: $Exports<'escope/powered-test/arguments'>;
}
declare module 'escope/powered-test/catch-scope.js' {
  declare module.exports: $Exports<'escope/powered-test/catch-scope'>;
}
declare module 'escope/powered-test/es6-arrow-function-expression.js' {
  declare module.exports: $Exports<'escope/powered-test/es6-arrow-function-expression'>;
}
declare module 'escope/powered-test/es6-block-scope.js' {
  declare module.exports: $Exports<'escope/powered-test/es6-block-scope'>;
}
declare module 'escope/powered-test/es6-catch.js' {
  declare module.exports: $Exports<'escope/powered-test/es6-catch'>;
}
declare module 'escope/powered-test/es6-class.js' {
  declare module.exports: $Exports<'escope/powered-test/es6-class'>;
}
declare module 'escope/powered-test/es6-destructuring-assignments.js' {
  declare module.exports: $Exports<'escope/powered-test/es6-destructuring-assignments'>;
}
declare module 'escope/powered-test/es6-export.js' {
  declare module.exports: $Exports<'escope/powered-test/es6-export'>;
}
declare module 'escope/powered-test/es6-import.js' {
  declare module.exports: $Exports<'escope/powered-test/es6-import'>;
}
declare module 'escope/powered-test/es6-iteration-scope.js' {
  declare module.exports: $Exports<'escope/powered-test/es6-iteration-scope'>;
}
declare module 'escope/powered-test/es6-object.js' {
  declare module.exports: $Exports<'escope/powered-test/es6-object'>;
}
declare module 'escope/powered-test/es6-rest-args.js' {
  declare module.exports: $Exports<'escope/powered-test/es6-rest-args'>;
}
declare module 'escope/powered-test/es6-switch.js' {
  declare module.exports: $Exports<'escope/powered-test/es6-switch'>;
}
declare module 'escope/powered-test/es6-template-literal.js' {
  declare module.exports: $Exports<'escope/powered-test/es6-template-literal'>;
}
declare module 'escope/powered-test/function-expression-name.js' {
  declare module.exports: $Exports<'escope/powered-test/function-expression-name'>;
}
declare module 'escope/powered-test/global-increment.js' {
  declare module.exports: $Exports<'escope/powered-test/global-increment'>;
}
declare module 'escope/powered-test/implicit-global-reference.js' {
  declare module.exports: $Exports<'escope/powered-test/implicit-global-reference'>;
}
declare module 'escope/powered-test/label-children.js' {
  declare module.exports: $Exports<'escope/powered-test/label-children'>;
}
declare module 'escope/powered-test/label.js' {
  declare module.exports: $Exports<'escope/powered-test/label'>;
}
declare module 'escope/powered-test/nodejs-scope.js' {
  declare module.exports: $Exports<'escope/powered-test/nodejs-scope'>;
}
declare module 'escope/powered-test/object-expression.js' {
  declare module.exports: $Exports<'escope/powered-test/object-expression'>;
}
declare module 'escope/powered-test/optimistic.js' {
  declare module.exports: $Exports<'escope/powered-test/optimistic'>;
}
declare module 'escope/powered-test/with-scope.js' {
  declare module.exports: $Exports<'escope/powered-test/with-scope'>;
}
declare module 'escope/src/definition.js' {
  declare module.exports: $Exports<'escope/src/definition'>;
}
declare module 'escope/src/index.js' {
  declare module.exports: $Exports<'escope/src/index'>;
}
declare module 'escope/src/pattern-visitor.js' {
  declare module.exports: $Exports<'escope/src/pattern-visitor'>;
}
declare module 'escope/src/reference.js' {
  declare module.exports: $Exports<'escope/src/reference'>;
}
declare module 'escope/src/referencer.js' {
  declare module.exports: $Exports<'escope/src/referencer'>;
}
declare module 'escope/src/scope-manager.js' {
  declare module.exports: $Exports<'escope/src/scope-manager'>;
}
declare module 'escope/src/scope.js' {
  declare module.exports: $Exports<'escope/src/scope'>;
}
declare module 'escope/src/variable.js' {
  declare module.exports: $Exports<'escope/src/variable'>;
}
declare module 'escope/third_party/espree.js' {
  declare module.exports: $Exports<'escope/third_party/espree'>;
}
