// flow-typed signature: 70921b648ed3ee3529e1ec6a6f6353b0
// flow-typed version: <<STUB>>/express-http-proxy_v^1.0.6/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-http-proxy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-http-proxy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-http-proxy/app/steps/buildProxyReq' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/copyProxyResHeadersToUserRes' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/decorateProxyReqBody' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/decorateProxyReqOpts' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/decorateUserRes' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/maybeSkipToNextHandler' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/prepareProxyReq' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/resolveProxyHost' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/resolveProxyReqPath' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/sendProxyRequest' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/sendUserRes' {
  declare module.exports: any;
}

declare module 'express-http-proxy/lib/as' {
  declare module.exports: any;
}

declare module 'express-http-proxy/lib/chunkLength' {
  declare module.exports: any;
}

declare module 'express-http-proxy/lib/isUnset' {
  declare module.exports: any;
}

declare module 'express-http-proxy/lib/mockHTTP' {
  declare module.exports: any;
}

declare module 'express-http-proxy/lib/requestOptions' {
  declare module.exports: any;
}

declare module 'express-http-proxy/lib/resolveOptions' {
  declare module.exports: any;
}

declare module 'express-http-proxy/lib/scopeContainer' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/bodyEncoding' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/catchingErrors' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/cookies' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/decorateRequest' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/headers' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/host' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/https' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/integration/proxyReqPathResolver' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/maybeSkipToNextHandler' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/middlewareCompatibility' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/params' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/path' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/port' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/preserveHostHdr' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/session' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/status' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/support/proxyTarget' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/timeout' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/unit/resolveProxyReqPath' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/urlParsing' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/userResDecorator' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/verbs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-http-proxy/app/steps/buildProxyReq.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/buildProxyReq'>;
}
declare module 'express-http-proxy/app/steps/copyProxyResHeadersToUserRes.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/copyProxyResHeadersToUserRes'>;
}
declare module 'express-http-proxy/app/steps/decorateProxyReqBody.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/decorateProxyReqBody'>;
}
declare module 'express-http-proxy/app/steps/decorateProxyReqOpts.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/decorateProxyReqOpts'>;
}
declare module 'express-http-proxy/app/steps/decorateUserRes.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/decorateUserRes'>;
}
declare module 'express-http-proxy/app/steps/maybeSkipToNextHandler.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/maybeSkipToNextHandler'>;
}
declare module 'express-http-proxy/app/steps/prepareProxyReq.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/prepareProxyReq'>;
}
declare module 'express-http-proxy/app/steps/resolveProxyHost.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/resolveProxyHost'>;
}
declare module 'express-http-proxy/app/steps/resolveProxyReqPath.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/resolveProxyReqPath'>;
}
declare module 'express-http-proxy/app/steps/sendProxyRequest.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/sendProxyRequest'>;
}
declare module 'express-http-proxy/app/steps/sendUserRes.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/sendUserRes'>;
}
declare module 'express-http-proxy/index' {
  declare module.exports: $Exports<'express-http-proxy'>;
}
declare module 'express-http-proxy/index.js' {
  declare module.exports: $Exports<'express-http-proxy'>;
}
declare module 'express-http-proxy/lib/as.js' {
  declare module.exports: $Exports<'express-http-proxy/lib/as'>;
}
declare module 'express-http-proxy/lib/chunkLength.js' {
  declare module.exports: $Exports<'express-http-proxy/lib/chunkLength'>;
}
declare module 'express-http-proxy/lib/isUnset.js' {
  declare module.exports: $Exports<'express-http-proxy/lib/isUnset'>;
}
declare module 'express-http-proxy/lib/mockHTTP.js' {
  declare module.exports: $Exports<'express-http-proxy/lib/mockHTTP'>;
}
declare module 'express-http-proxy/lib/requestOptions.js' {
  declare module.exports: $Exports<'express-http-proxy/lib/requestOptions'>;
}
declare module 'express-http-proxy/lib/resolveOptions.js' {
  declare module.exports: $Exports<'express-http-proxy/lib/resolveOptions'>;
}
declare module 'express-http-proxy/lib/scopeContainer.js' {
  declare module.exports: $Exports<'express-http-proxy/lib/scopeContainer'>;
}
declare module 'express-http-proxy/test/bodyEncoding.js' {
  declare module.exports: $Exports<'express-http-proxy/test/bodyEncoding'>;
}
declare module 'express-http-proxy/test/catchingErrors.js' {
  declare module.exports: $Exports<'express-http-proxy/test/catchingErrors'>;
}
declare module 'express-http-proxy/test/cookies.js' {
  declare module.exports: $Exports<'express-http-proxy/test/cookies'>;
}
declare module 'express-http-proxy/test/decorateRequest.js' {
  declare module.exports: $Exports<'express-http-proxy/test/decorateRequest'>;
}
declare module 'express-http-proxy/test/headers.js' {
  declare module.exports: $Exports<'express-http-proxy/test/headers'>;
}
declare module 'express-http-proxy/test/host.js' {
  declare module.exports: $Exports<'express-http-proxy/test/host'>;
}
declare module 'express-http-proxy/test/https.js' {
  declare module.exports: $Exports<'express-http-proxy/test/https'>;
}
declare module 'express-http-proxy/test/integration/proxyReqPathResolver.js' {
  declare module.exports: $Exports<'express-http-proxy/test/integration/proxyReqPathResolver'>;
}
declare module 'express-http-proxy/test/maybeSkipToNextHandler.js' {
  declare module.exports: $Exports<'express-http-proxy/test/maybeSkipToNextHandler'>;
}
declare module 'express-http-proxy/test/middlewareCompatibility.js' {
  declare module.exports: $Exports<'express-http-proxy/test/middlewareCompatibility'>;
}
declare module 'express-http-proxy/test/params.js' {
  declare module.exports: $Exports<'express-http-proxy/test/params'>;
}
declare module 'express-http-proxy/test/path.js' {
  declare module.exports: $Exports<'express-http-proxy/test/path'>;
}
declare module 'express-http-proxy/test/port.js' {
  declare module.exports: $Exports<'express-http-proxy/test/port'>;
}
declare module 'express-http-proxy/test/preserveHostHdr.js' {
  declare module.exports: $Exports<'express-http-proxy/test/preserveHostHdr'>;
}
declare module 'express-http-proxy/test/session.js' {
  declare module.exports: $Exports<'express-http-proxy/test/session'>;
}
declare module 'express-http-proxy/test/status.js' {
  declare module.exports: $Exports<'express-http-proxy/test/status'>;
}
declare module 'express-http-proxy/test/support/proxyTarget.js' {
  declare module.exports: $Exports<'express-http-proxy/test/support/proxyTarget'>;
}
declare module 'express-http-proxy/test/timeout.js' {
  declare module.exports: $Exports<'express-http-proxy/test/timeout'>;
}
declare module 'express-http-proxy/test/unit/resolveProxyReqPath.js' {
  declare module.exports: $Exports<'express-http-proxy/test/unit/resolveProxyReqPath'>;
}
declare module 'express-http-proxy/test/urlParsing.js' {
  declare module.exports: $Exports<'express-http-proxy/test/urlParsing'>;
}
declare module 'express-http-proxy/test/userResDecorator.js' {
  declare module.exports: $Exports<'express-http-proxy/test/userResDecorator'>;
}
declare module 'express-http-proxy/test/verbs.js' {
  declare module.exports: $Exports<'express-http-proxy/test/verbs'>;
}
