// flow-typed signature: d6050d0f88c7182f4e110f22a373129a
// flow-typed version: <<STUB>>/fastclick_v1.0.6/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fastclick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fastclick' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fastclick/lib/fastclick' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fastclick/lib/fastclick.js' {
  declare module.exports: $Exports<'fastclick/lib/fastclick'>;
}
