// flow-typed signature: c32fb03500f94e189807ca8f2a021e20
// flow-typed version: <<STUB>>/open_v^0.0.5/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'open'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'open' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'open/lib/open' {
  declare module.exports: any;
}

// Filename aliases
declare module 'open/lib/open.js' {
  declare module.exports: $Exports<'open/lib/open'>;
}
