// flow-typed signature: 1f7186f523696bf87caf98b619ce5bdd
// flow-typed version: <<STUB>>/react-relay-network-layer_v^2.0.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-relay-network-layer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-relay-network-layer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-relay-network-layer/es/createRequestError' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/es/express-middleware/graphqlBatchHTTPWrapper' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/es/fetchWithMiddleware' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/es/index' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/es/middleware/auth' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/es/middleware/batch' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/es/middleware/defer' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/es/middleware/gqErrors' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/es/middleware/logger' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/es/middleware/perf' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/es/middleware/retry' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/es/middleware/url' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/es/relayMutation' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/es/relayNetworkLayer' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/es/relayQueries' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/es/utils' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/lib/createRequestError' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/lib/express-middleware/graphqlBatchHTTPWrapper' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/lib/fetchWithMiddleware' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/lib/index' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/lib/middleware/auth' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/lib/middleware/batch' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/lib/middleware/defer' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/lib/middleware/gqErrors' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/lib/middleware/logger' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/lib/middleware/perf' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/lib/middleware/retry' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/lib/middleware/url' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/lib/relayMutation' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/lib/relayNetworkLayer' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/lib/relayQueries' {
  declare module.exports: any;
}

declare module 'react-relay-network-layer/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-relay-network-layer/es/createRequestError.js' {
  declare module.exports: $Exports<'react-relay-network-layer/es/createRequestError'>;
}
declare module 'react-relay-network-layer/es/express-middleware/graphqlBatchHTTPWrapper.js' {
  declare module.exports: $Exports<'react-relay-network-layer/es/express-middleware/graphqlBatchHTTPWrapper'>;
}
declare module 'react-relay-network-layer/es/fetchWithMiddleware.js' {
  declare module.exports: $Exports<'react-relay-network-layer/es/fetchWithMiddleware'>;
}
declare module 'react-relay-network-layer/es/index.js' {
  declare module.exports: $Exports<'react-relay-network-layer/es/index'>;
}
declare module 'react-relay-network-layer/es/middleware/auth.js' {
  declare module.exports: $Exports<'react-relay-network-layer/es/middleware/auth'>;
}
declare module 'react-relay-network-layer/es/middleware/batch.js' {
  declare module.exports: $Exports<'react-relay-network-layer/es/middleware/batch'>;
}
declare module 'react-relay-network-layer/es/middleware/defer.js' {
  declare module.exports: $Exports<'react-relay-network-layer/es/middleware/defer'>;
}
declare module 'react-relay-network-layer/es/middleware/gqErrors.js' {
  declare module.exports: $Exports<'react-relay-network-layer/es/middleware/gqErrors'>;
}
declare module 'react-relay-network-layer/es/middleware/logger.js' {
  declare module.exports: $Exports<'react-relay-network-layer/es/middleware/logger'>;
}
declare module 'react-relay-network-layer/es/middleware/perf.js' {
  declare module.exports: $Exports<'react-relay-network-layer/es/middleware/perf'>;
}
declare module 'react-relay-network-layer/es/middleware/retry.js' {
  declare module.exports: $Exports<'react-relay-network-layer/es/middleware/retry'>;
}
declare module 'react-relay-network-layer/es/middleware/url.js' {
  declare module.exports: $Exports<'react-relay-network-layer/es/middleware/url'>;
}
declare module 'react-relay-network-layer/es/relayMutation.js' {
  declare module.exports: $Exports<'react-relay-network-layer/es/relayMutation'>;
}
declare module 'react-relay-network-layer/es/relayNetworkLayer.js' {
  declare module.exports: $Exports<'react-relay-network-layer/es/relayNetworkLayer'>;
}
declare module 'react-relay-network-layer/es/relayQueries.js' {
  declare module.exports: $Exports<'react-relay-network-layer/es/relayQueries'>;
}
declare module 'react-relay-network-layer/es/utils.js' {
  declare module.exports: $Exports<'react-relay-network-layer/es/utils'>;
}
declare module 'react-relay-network-layer/lib/createRequestError.js' {
  declare module.exports: $Exports<'react-relay-network-layer/lib/createRequestError'>;
}
declare module 'react-relay-network-layer/lib/express-middleware/graphqlBatchHTTPWrapper.js' {
  declare module.exports: $Exports<'react-relay-network-layer/lib/express-middleware/graphqlBatchHTTPWrapper'>;
}
declare module 'react-relay-network-layer/lib/fetchWithMiddleware.js' {
  declare module.exports: $Exports<'react-relay-network-layer/lib/fetchWithMiddleware'>;
}
declare module 'react-relay-network-layer/lib/index.js' {
  declare module.exports: $Exports<'react-relay-network-layer/lib/index'>;
}
declare module 'react-relay-network-layer/lib/middleware/auth.js' {
  declare module.exports: $Exports<'react-relay-network-layer/lib/middleware/auth'>;
}
declare module 'react-relay-network-layer/lib/middleware/batch.js' {
  declare module.exports: $Exports<'react-relay-network-layer/lib/middleware/batch'>;
}
declare module 'react-relay-network-layer/lib/middleware/defer.js' {
  declare module.exports: $Exports<'react-relay-network-layer/lib/middleware/defer'>;
}
declare module 'react-relay-network-layer/lib/middleware/gqErrors.js' {
  declare module.exports: $Exports<'react-relay-network-layer/lib/middleware/gqErrors'>;
}
declare module 'react-relay-network-layer/lib/middleware/logger.js' {
  declare module.exports: $Exports<'react-relay-network-layer/lib/middleware/logger'>;
}
declare module 'react-relay-network-layer/lib/middleware/perf.js' {
  declare module.exports: $Exports<'react-relay-network-layer/lib/middleware/perf'>;
}
declare module 'react-relay-network-layer/lib/middleware/retry.js' {
  declare module.exports: $Exports<'react-relay-network-layer/lib/middleware/retry'>;
}
declare module 'react-relay-network-layer/lib/middleware/url.js' {
  declare module.exports: $Exports<'react-relay-network-layer/lib/middleware/url'>;
}
declare module 'react-relay-network-layer/lib/relayMutation.js' {
  declare module.exports: $Exports<'react-relay-network-layer/lib/relayMutation'>;
}
declare module 'react-relay-network-layer/lib/relayNetworkLayer.js' {
  declare module.exports: $Exports<'react-relay-network-layer/lib/relayNetworkLayer'>;
}
declare module 'react-relay-network-layer/lib/relayQueries.js' {
  declare module.exports: $Exports<'react-relay-network-layer/lib/relayQueries'>;
}
declare module 'react-relay-network-layer/lib/utils.js' {
  declare module.exports: $Exports<'react-relay-network-layer/lib/utils'>;
}
